name: 'Azure Container Registry Build Action by MDPNetTeam'
branding:
  icon: 'upload-cloud'
  color: 'red'
author: 'Clark159'
description: 'GitHub Action for building Azure Container Registry'

runs:
  using: 'composite'
  steps:
  
  - name: 'Login Azure CLI'
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
      
  - name: 'Checkout GitHub Repository'
    uses: actions/checkout@v4 
